# Generated by Django 3.0.4 on 2020-03-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_todolist_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='item',
            field=models.CharField(max_length=1000),
        ),
    ]
