# Generated by Django 3.0.4 on 2020-03-12 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_auto_20200312_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
