# Generated by Django 3.0.4 on 2020-03-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_boardlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardlist',
            name='board_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='boardlist',
            name='board_url',
            field=models.SlugField(max_length=20),
        ),
    ]
