# Generated by Django 3.0.4 on 2020-03-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_auto_20200313_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardlist',
            name='board_url',
        ),
    ]
