# Generated by Django 3.0.4 on 2020-03-14 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0009_remove_boardlist_board_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='board_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo_list.BoardList'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardlist',
            name='board_name',
            field=models.CharField(max_length=50),
        ),
    ]
