# Generated by Django 3.0.4 on 2020-03-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0010_auto_20200314_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='board_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='todo_list.BoardList'),
        ),
    ]
